config/routes.rb
Rails.application.routes.draw do
  devise_for :pages, :controllers => {:registrations => "pages/registrations"}

  get 'pages/home'
  get 'pages/about_us'
  get 'pages/blog'
  get 'pages/contact_us'
  
  resources :posts
  resources :contact, only:[:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, presence: true, length:{maximum:25}
	Valid_Email= /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i
	validates :email, presence: true, format: {with:Valid_Email}
	validates :message, presence: true, length:{maximum:125}
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def new
  	 @contact=Contact.new
    end

    def create
    	@contact=Contact.new(contact_param)

      if @contact.valid?
        ContactMailer.new_contact(@contact).deliver
	      flash[:sucess]="Thanks for you respose"
	      redirect_to root_path

      else
	      flash[:alert]="cannot send message"
	      render 'new'
      end
    end
    
  private
 
    def contact_param
 	   params.require(:contact).permit(:name,:email,:message)
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<h2>Contact us</h2>

<%= form_for(@contact, url: contact_index_path) do |f| %>
  <form>
  <div class="form-group">
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name,autofocus: true,class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email,  autocomplete: "email",class: 'form-control' %>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message,class: 'form-control' %>
  </div>
</div>
    <%= f.submit "Submit",class: "btn btn-primary"%>
 </form>
<% end %>
</div>
</div>