config/routes.rb
Rails.application.routes.draw do
  devise_for :pages, :controllers => {:registrations => "pages/registrations"}

  get 'pages/home'
  get 'pages/about_us'
  get 'pages/blog'
  get 'pages/contact_us'
  
  resources :posts
  resources :contact, only:[:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
<div class="container">
<nav>
	<ul class="navbar-right">
<li>footer</li>
</ul>
</nav>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home" , pages_home_path %></li> 
				<li><%= link_to "About us", pages_about_us_path %></li> 
				<li><%= link_to "Contact us", new_contact_path %></li> 

			   <% if page_signed_in? %>
			   	<li><%= link_to "Blog", pages_blog_path %></li>
				<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account</a>
					<ul class="dropdown-menu">
						<li><%= link_to "new blog", new_post_path %></li>
						<li><%= link_to "My Posts", posts_path %></li>
						<li><%= link_to "Logout", destroy_page_session_path, method: :delete %>
						</li>
						<td><%= link_to "Deactivate",  method: :delete, data: { confirm: "You sure?"} %>
 					</ul>
				</li>
			   <% else %>
				<li><%= link_to "Login", new_page_session_path %></li>
			   <% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>